### ISSUE TITLE
Mulighet for å legge til nye inntektsposter

### ISSUE THREAD

**Issue by nicokk** [navikt/dagpenger-regel-ui#13]
Per nå er det kun mulig å redigere beløp for inntektsposter som allerede finnes. Det er et behov for at nye inntektsposter skal kunne legges til på en måned.

**Comment by PetterRuud** [comment]
Ja, vi må gjøre om til å bruke fieldarray, https://jaredpalmer.com/formik/docs/api/fieldarray.

Kan se på det på mandag

**Comment by PetterRuud** [comment]
![image](https://user-images.githubusercontent.com/1826786/57854400-72950e80-77e8-11e9-8ae3-172e76c88fa7.png)

Vi trenger litt designstøtte på denne tror jeg. 

Hva trenger den nye inntektsposten å inneholde

`
beloep: '666.66',
  beskrivelse: 'Test ny',
  fordel: 'kontantytelse',
  informasjonsstatus: 'InngaarAlltid',
  inngaarIGrunnlagForTrekk: true,
  inntektType: 'LOENNSINNTEKT',
  inntektskilde: 'A-ordningen',
  inntektsmottaker: {
    aktoerType: 'NATURLIG_IDENT',
    identifikator: '99999999999',
  },
  inntektsperiodetype: 'Maaned',
  inntektsstatus: 'LoependeInnrapportert',
  leveringstidspunkt: '2019-02',
  opplysningspliktig: {
    aktoerType: 'ORGANISASJON',
    identifikator: '1111111',
  },
  utbetaltIMaaned: '2017-09',
  utloeserArbeidsgiveravgift: true,
  virksomhet: {
    aktoerType: 'ORGANISASJON',
    identifikator: '1111111',
    navn: 'Enenenenen',
  },
`
