### ISSUE TITLE
Legge til validering på felter

### ISSUE THREAD

**Issue by PetterRuud** [navikt/dagpenger-regel-ui#8]
Legger til validering på felter. 

- required
- er desimal (legger på normalize på felter slik at hvis man bare skriver int så legges det på ",00")

Spørsmål.

Hvordan vil backend ha tallene, hvis det er desimaler vil frontend sende de som en string
"34323,34"

**Comment by geiralund** [comment]
Backend tar i mot det som strenger (BigDecimal) - det som er viktig er å ikke "miste" noen desimaler på veien.
